[package]
name = "guzzler"
version = "0.1.0"
edition = "2024"

#[profile.release]
#codegen-units = 1
#lto = true

[dependencies]
clap = { version = "4.0", features = ["derive"] }
libc = "0.2"
rand = "0.8"
